// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMj7SRw5b1DMQkPvMhg4xpHvlu1TNXQxA',
    appId: '1:450722568519:web:a499d13944079ba36cd462',
    messagingSenderId: '450722568519',
    projectId: 'web-rtc-flutter-23dc9',
    authDomain: 'web-rtc-flutter-23dc9.firebaseapp.com',
    storageBucket: 'web-rtc-flutter-23dc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfvtsTAhIiwgbWKXTcuC1wbh8v53lU3_M',
    appId: '1:450722568519:android:02b73f6169b41b706cd462',
    messagingSenderId: '450722568519',
    projectId: 'web-rtc-flutter-23dc9',
    storageBucket: 'web-rtc-flutter-23dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF2raIj15_2J7PR3j7yu12efC3bZcQkU4',
    appId: '1:450722568519:ios:3ea244b9d504b6db6cd462',
    messagingSenderId: '450722568519',
    projectId: 'web-rtc-flutter-23dc9',
    storageBucket: 'web-rtc-flutter-23dc9.appspot.com',
    iosClientId: '450722568519-lndnjke8ae4173vqm88mi91d7pad0gll.apps.googleusercontent.com',
    iosBundleId: 'com.example.webrtcFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF2raIj15_2J7PR3j7yu12efC3bZcQkU4',
    appId: '1:450722568519:ios:05f6ae30cec3d6566cd462',
    messagingSenderId: '450722568519',
    projectId: 'web-rtc-flutter-23dc9',
    storageBucket: 'web-rtc-flutter-23dc9.appspot.com',
    iosClientId: '450722568519-1nd5a47uoiqt79gig387nqitsttvqi3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebrtc',
  );
}
